// <auto-generated />
using System;
using EFLinq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFLinq.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219102200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFLinq.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptNo"));

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptNo");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptNo = 10,
                            DName = "ACCOUNTING",
                            Loc = "NEW YORK"
                        },
                        new
                        {
                            DeptNo = 20,
                            DName = "RESEARCH",
                            Loc = "DALLAS"
                        },
                        new
                        {
                            DeptNo = 30,
                            DName = "SALES",
                            Loc = "CHICAGO"
                        },
                        new
                        {
                            DeptNo = 40,
                            DName = "OPERATIONS",
                            Loc = "BOSTON"
                        });
                });

            modelBuilder.Entity("EFLinq.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpNo"));

                    b.Property<decimal?>("Comm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mgr")
                        .HasColumnType("int");

                    b.Property<decimal>("Sal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpNo");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpNo = 7369,
                            DeptNo = 20,
                            EName = "SMITH",
                            HireDate = new DateTime(1980, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "CLERK",
                            Mgr = 7902,
                            Sal = 800m
                        },
                        new
                        {
                            EmpNo = 7499,
                            Comm = 300m,
                            DeptNo = 30,
                            EName = "ALLEN",
                            HireDate = new DateTime(1981, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "SALESMAN",
                            Mgr = 7698,
                            Sal = 1600m
                        },
                        new
                        {
                            EmpNo = 7521,
                            Comm = 500m,
                            DeptNo = 30,
                            EName = "WARD",
                            HireDate = new DateTime(1981, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "SALESMAN",
                            Mgr = 7698,
                            Sal = 1250m
                        },
                        new
                        {
                            EmpNo = 7566,
                            DeptNo = 20,
                            EName = "JONES",
                            HireDate = new DateTime(1981, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "MANAGER",
                            Mgr = 7839,
                            Sal = 2975m
                        },
                        new
                        {
                            EmpNo = 7654,
                            Comm = 1400m,
                            DeptNo = 30,
                            EName = "MARTIN",
                            HireDate = new DateTime(1981, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "SALESMAN",
                            Mgr = 7698,
                            Sal = 1250m
                        },
                        new
                        {
                            EmpNo = 7698,
                            DeptNo = 30,
                            EName = "BLAKE",
                            HireDate = new DateTime(1981, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "MANAGER",
                            Mgr = 7839,
                            Sal = 2850m
                        },
                        new
                        {
                            EmpNo = 7782,
                            DeptNo = 10,
                            EName = "CLARK",
                            HireDate = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "MANAGER",
                            Mgr = 7839,
                            Sal = 2450m
                        },
                        new
                        {
                            EmpNo = 7788,
                            DeptNo = 20,
                            EName = "SCOTT",
                            HireDate = new DateTime(1987, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "ANALYST",
                            Mgr = 7566,
                            Sal = 3000m
                        },
                        new
                        {
                            EmpNo = 7839,
                            DeptNo = 10,
                            EName = "KING",
                            HireDate = new DateTime(1981, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "PRESIDENT",
                            Sal = 5000m
                        },
                        new
                        {
                            EmpNo = 7844,
                            Comm = 0m,
                            DeptNo = 30,
                            EName = "TURNER",
                            HireDate = new DateTime(1981, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "SALESMAN",
                            Mgr = 7698,
                            Sal = 1500m
                        },
                        new
                        {
                            EmpNo = 7876,
                            DeptNo = 20,
                            EName = "ADAMS",
                            HireDate = new DateTime(1987, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "CLERK",
                            Mgr = 7788,
                            Sal = 1100m
                        },
                        new
                        {
                            EmpNo = 7900,
                            DeptNo = 30,
                            EName = "JAMES",
                            HireDate = new DateTime(1981, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "CLERK",
                            Mgr = 7698,
                            Sal = 950m
                        },
                        new
                        {
                            EmpNo = 7902,
                            DeptNo = 20,
                            EName = "FORD",
                            HireDate = new DateTime(1981, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "ANALYST",
                            Mgr = 7566,
                            Sal = 3000m
                        },
                        new
                        {
                            EmpNo = 7934,
                            DeptNo = 10,
                            EName = "MILLER",
                            HireDate = new DateTime(1982, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "CLERK",
                            Mgr = 7782,
                            Sal = 1300m
                        });
                });

            modelBuilder.Entity("EFLinq.Employee", b =>
                {
                    b.HasOne("EFLinq.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFLinq.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
