using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceManagement.DAL.Models
{
    /// <summary>
    /// Core invoice entity. An invoice can be created manually or from an accepted Quotation.
    /// 
    /// RELATIONSHIPS:
    ///   Invoice (N) ──────────────── (1) Customer     [via CustomerId — external module ref]
    ///   Invoice (N) ──────────────── (1) Quotation    [via QuoteId   — external module ref, nullable]
    ///   Invoice (1) ──────────────── (N) InvoiceLineItem  [Cascade Delete]
    ///   Invoice (1) ──────────────── (N) Payment          [Cascade Delete]
    /// 
    /// NOTE: CustomerId and QuoteId reference Customer Management and Quotation Management
    ///       modules respectively. No navigation properties here since they are separate projects.
    ///       In Phase 2 (API), these will be resolved via HTTP calls or a shared database.
    /// </summary>
    [Table("Invoices")]
    public class Invoice
    {
        // ── Primary Key ──────────────────────────────────────────────────────
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InvoiceId { get; set; }

        // ── Invoice Identity ─────────────────────────────────────────────────
        /// <summary>
        /// Auto-generated by InvoiceNumberEngine. Format: INV-YYYYMM-XXXXX
        /// e.g., INV-202502-00001
        /// </summary>
        [Required(ErrorMessage = "Invoice number is required.")]
        [MaxLength(20, ErrorMessage = "Invoice number cannot exceed 20 characters.")]
        public string InvoiceNumber { get; set; } = string.Empty;

        // ── Cross-Module References (no navigation properties — separate projects) ──
        /// <summary>
        /// References Customer in Customer Management module.
        /// </summary>
        [Required(ErrorMessage = "Customer is required.")]
        public int CustomerId { get; set; }

        /// <summary>
        /// References Quotation in Quotation Management module. Nullable — invoice may be manual.
        /// </summary>
        public int? QuoteId { get; set; }

        // ── Status & Terms ───────────────────────────────────────────────────
        /// <summary>
        /// Stored as string in DB for readability. Validated via InvoiceStatusValidator.
        /// Valid transitions enforced in BLL: Draft→Sent→Paid/PartiallyPaid/Overdue/Cancelled
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string Status { get; set; } = InvoiceStatus.Draft.ToString();

        /// <summary>
        /// Payment terms determine DueDate offset from InvoiceDate.
        /// Stored as string for readability.
        /// </summary>
        [Required]
        [MaxLength(15)]
        public string PaymentTerms { get; set; } = Models.PaymentTerms.Net30.ToString();

        // ── Dates ────────────────────────────────────────────────────────────
        [Required]
        public DateTime InvoiceDate { get; set; }

        /// <summary>
        /// Calculated by InvoiceCalculationEngine based on InvoiceDate + PaymentTerms.
        /// </summary>
        [Required]
        public DateTime DueDate { get; set; }

        // ── Recurring Invoice Support ────────────────────────────────────────
        public bool IsRecurring { get; set; } = false;

        /// <summary>
        /// Recurrence interval in days. Null if not recurring.
        /// e.g., 30 = monthly, 365 = yearly
        /// </summary>
        public int? RecurrenceIntervalDays { get; set; }

        /// <summary>
        /// Date when the next recurring invoice should be generated.
        /// </summary>
        public DateTime? NextInvoiceDate { get; set; }

        // ── Financials ───────────────────────────────────────────────────────
        /// <summary>
        /// Sum of all LineItem LineTotals before invoice-level discount.
        /// Calculated by InvoiceCalculationEngine — do NOT set manually.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal SubTotal { get; set; }

        /// <summary>
        /// Invoice-level discount amount (not percentage).
        /// Line-level discounts are stored on InvoiceLineItem.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        [Range(0, double.MaxValue, ErrorMessage = "Discount cannot be negative.")]
        public decimal Discount { get; set; }

        /// <summary>
        /// Total tax calculated across all line items.
        /// Calculated by InvoiceCalculationEngine.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal Tax { get; set; }

        /// <summary>
        /// GrandTotal = SubTotal - Discount + Tax.
        /// Calculated by InvoiceCalculationEngine — do NOT set manually.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal GrandTotal { get; set; }

        /// <summary>
        /// Running total of payments received against this invoice.
        /// Updated by PaymentService each time a payment is recorded.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal AmountPaid { get; set; } = 0;

        /// <summary>
        /// OutstandingBalance = GrandTotal - AmountPaid.
        /// Calculated property — stored for performance and aging queries.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal OutstandingBalance { get; set; }

        // ── Notes & Terms ────────────────────────────────────────────────────
        [MaxLength(500)]
        public string? Notes { get; set; }

        [MaxLength(1000)]
        public string? TermsAndConditions { get; set; }

        // ── Archive / Soft Delete ────────────────────────────────────────────
        /// <summary>
        /// Soft delete flag. Archived invoices are excluded from active queries.
        /// Use InvoiceService.ArchiveInvoice() — do NOT set directly.
        /// </summary>
        public bool IsArchived { get; set; } = false;

        public DateTime? ArchivedDate { get; set; }

        // ── Audit Fields ─────────────────────────────────────────────────────
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        public DateTime? ModifiedDate { get; set; }

        [MaxLength(100)]
        public string? CreatedBy { get; set; }

        // ── Navigation: One Invoice → Many InvoiceLineItems ──────────────────
        // Cascade: Delete (removing an invoice removes all its line items)
        public ICollection<InvoiceLineItem> LineItems { get; set; } = new List<InvoiceLineItem>();

        // ── Navigation: One Invoice → Many Payments ──────────────────────────
        // Cascade: Delete (removing an invoice removes all payment records)
        public ICollection<Payment> Payments { get; set; } = new List<Payment>();
    }
}
